pipeline {
    agent any

    tools {
        python 'Python3'  
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/alx-backend-python/messaging_app.git',
                    branch: 'main',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Setup Python Env') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    triggers {
        // No auto triggers, pipeline runs manually
    }
}
